<a href="https://colab.research.google.com/github/lamiya123-art/internship/blob/main/E_commerce_sales.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib as mpl
import scipy as sp

In [11]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

After you mount your Google Drive and the file `ecommerce_sales.xlsx` is located in your Drive, please run the code below to load the data into a pandas DataFrame. Make sure to replace `'Path/to/your/ecommerce_sales.xlsx'` with the actual path to your file within Google Drive.

In [12]:
df = pd.read_excel('/content/drive/MyDrive/ecommerce_sales.xlsx')
display(df.head())

   OrderID       Date     Product     Category  Revenue Customer Location
0        1 2023-01-01       Phone  Electronics  1456.41               USA
1        2 2023-01-02  Headphones  Electronics   783.98             India
2        3 2023-01-03       Phone  Electronics  1295.32             India
3        4 2023-01-04       Phone  Accessories  1112.17             India
4        5 2023-01-05       Phone  Electronics   592.98                UK

In [6]:
df.head(10)

   OrderID       Date     Product     Category  Revenue Customer Location
0        1 2023-01-01       Phone  Electronics  1456.41               USA
1        2 2023-01-02  Headphones  Electronics   783.98             India
2        3 2023-01-03       Phone  Electronics  1295.32             India
3        4 2023-01-04       Phone  Accessories  1112.17             India
4        5 2023-01-05       Phone  Electronics   592.98                UK
5        6 2023-01-06  Headphones  Accessories  1569.39           Germany
6        7 2023-01-07  Headphones  Accessories  1176.29           Germany
7        8 2023-01-08      Tablet  Accessories   934.23           Germany
8        9 2023-01-09  Headphones  Electronics  1345.68               USA
9       10 2023-01-10  Headphones  Electronics  1612.86               USA

In [16]:
sales = df
print(sales.dtypes)

OrderID                       int64
Date                 datetime64[ns]
Product                      object
Category                     object
Revenue                     float64
Customer Location            object
dtype: object

In [17]:
df['Revenue'].dtype

dtype('float64')

In [18]:
df.size

6000

In [20]:
df.axes

[RangeIndex(start=0, stop=1000, step=1),
 Index(['OrderID', 'Date', 'Product', 'Category', 'Revenue',
        'Customer Location'],
       dtype='object')]

In [21]:
df.columns

Index(['OrderID', 'Date', 'Product', 'Category', 'Revenue',
       'Customer Location'],
      dtype='object')

In [22]:
df.columns.dtype

dtype('O')

In [23]:
#dataframe methods
df.describe()

           OrderID                 Date      Revenue
count  1000.000000                 1000  1000.000000
mean    500.500000  2024-05-14 12:00:00  1037.385430
min       1.000000  2023-01-01 00:00:00    51.150000
25%     250.750000  2023-09-07 18:00:00   553.015000
50%     500.500000  2024-05-14 12:00:00  1038.175000
75%     750.250000  2025-01-19 06:00:00  1530.832500
max    1000.000000  2025-09-26 00:00:00  1998.720000
std     288.819436                  NaN   566.863738

In [24]:
df.min()

OrderID                                1
Date                 2023-01-01 00:00:00
Product                       Headphones
Category                     Accessories
Revenue                            51.15
Customer Location                Germany
dtype: object

In [25]:
df.max()

OrderID                             1000
Date                 2025-09-26 00:00:00
Product                           Tablet
Category                     Electronics
Revenue                          1998.72
Customer Location                    USA
dtype: object

In [28]:
df['Revenue'].mean()

np.float64(1037.38543)

In [30]:
df['Revenue'].std()

566.8637375641349

In [39]:

df['Revenue'].mean()

np.float64(1037.38543)

In [40]:
df['Category'].count()

np.int64(1000)

In [42]:
df['Revenue'].mean()

np.float64(1037.38543)

In [43]:
#groupby
df_category = df.groupby(['Category'])

In [48]:
df_category = df.groupby(['Category'])
df_category['Revenue'].mean()

Category
Accessories    1046.387859
Electronics    1028.052974
Name: Revenue, dtype: float64

In [54]:
df.groupby('OrderID')['Customer Location'].first()

OrderID
1         USA
2       India
3       India
4       India
5          UK
        ...
996       USA
997     India
998       USA
999       USA
1000      USA
Name: Customer Location, Length: 1000, dtype: object

In [55]:
df.head()

   OrderID       Date     Product     Category  Revenue Customer Location
0        1 2023-01-01       Phone  Electronics  1456.41               USA
1        2 2023-01-02  Headphones  Electronics   783.98             India
2        3 2023-01-03       Phone  Electronics  1295.32             India
3        4 2023-01-04       Phone  Accessories  1112.17             India
4        5 2023-01-05       Phone  Electronics   592.98                UK

In [57]:
df_sub = df[df['Revenue'] > 1200]
print(df_sub)

     OrderID       Date     Product     Category  Revenue Customer Location
0          1 2023-01-01       Phone  Electronics  1456.41               USA
2          3 2023-01-03       Phone  Electronics  1295.32             India
5          6 2023-01-06  Headphones  Accessories  1569.39           Germany
8          9 2023-01-09  Headphones  Electronics  1345.68               USA
9         10 2023-01-10  Headphones  Electronics  1612.86               USA
..       ...        ...         ...          ...      ...               ...
987      988 2025-09-14      Tablet  Accessories  1570.80               USA
993      994 2025-09-20       Phone  Accessories  1636.98               USA
996      997 2025-09-23      Laptop  Accessories  1394.31             India
997      998 2025-09-24      Tablet  Electronics  1968.57               USA
999     1000 2025-09-26      Laptop  Electronics  1304.27               USA

[413 rows x 6 columns]

In [60]:
#slicing
df[['OrderID','Revenue']]

     OrderID  Revenue
0          1  1456.41
1          2   783.98
2          3  1295.32
3          4  1112.17
4          5   592.98
..       ...      ...
995      996   616.17
996      997  1394.31
997      998  1968.57
998      999  1182.97
999     1000  1304.27

[1000 rows x 2 columns]

In [62]:
df[10:21]

    OrderID       Date     Product     Category  Revenue Customer Location
10       11 2023-01-11       Phone  Accessories  1079.23                UK
11       12 2023-01-12      Tablet  Electronics  1647.35           Germany
12       13 2023-01-13      Laptop  Accessories   624.31             India
13       14 2023-01-14  Headphones  Accessories  1900.44               USA
14       15 2023-01-15      Tablet  Accessories  1708.56               USA
15       16 2023-01-16      Tablet  Electronics  1601.15                UK
16       17 2023-01-17  Headphones  Accessories  1084.59               USA
17       18 2023-01-18       Phone  Electronics  1571.53                UK
18       19 2023-01-19      Laptop  Accessories  1609.03               USA
19       20 2023-01-20       Phone  Accessories   980.28             India
20       21 2023-01-21  Headphones  Accessories   217.19               USA

In [63]:
df.loc[10:21,['OrderID','Revenue']]

    OrderID  Revenue
10       11  1079.23
11       12  1647.35
12       13   624.31
13       14  1900.44
14       15  1708.56
15       16  1601.15
16       17  1084.59
17       18  1571.53
18       19  1609.03
19       20   980.28
20       21   217.19
21       22  1159.40

In [64]:
#sorting
df_sorted = df.sort_values(by='Revenue')
print(df_sorted)

     OrderID       Date     Product     Category  Revenue Customer Location
462      463 2024-04-07       Phone  Accessories    51.15                UK
29        30 2023-01-30      Tablet  Electronics    53.30           Germany
298      299 2023-10-26       Phone  Electronics    54.52               USA
457      458 2024-04-02      Laptop  Electronics    58.03               USA
659      660 2024-10-21      Laptop  Electronics    59.56           Germany
..       ...        ...         ...          ...      ...               ...
439      440 2024-03-15      Tablet  Electronics  1991.33               USA
435      436 2024-03-11  Headphones  Electronics  1991.35                UK
909      910 2025-06-28      Tablet  Accessories  1992.91               USA
791      792 2025-03-02  Headphones  Electronics  1994.93             India
827      828 2025-04-07  Headphones  Accessories  1998.72             India

[1000 rows x 6 columns]

In [65]:
df_sorted = df.sort_values(by=['Revenue','OrderID'])
print(df_sorted)

     OrderID       Date     Product     Category  Revenue Customer Location
462      463 2024-04-07       Phone  Accessories    51.15                UK
29        30 2023-01-30      Tablet  Electronics    53.30           Germany
298      299 2023-10-26       Phone  Electronics    54.52               USA
457      458 2024-04-02      Laptop  Electronics    58.03               USA
659      660 2024-10-21      Laptop  Electronics    59.56           Germany
..       ...        ...         ...          ...      ...               ...
439      440 2024-03-15      Tablet  Electronics  1991.33               USA
435      436 2024-03-11  Headphones  Electronics  1991.35                UK
909      910 2025-06-28      Tablet  Accessories  1992.91               USA
791      792 2025-03-02  Headphones  Electronics  1994.93             India
827      828 2025-04-07  Headphones  Accessories  1998.72             India

[1000 rows x 6 columns]

In [67]:
df=df.isnull()
df.head()

   OrderID   Date  Product  Category  Revenue  Customer Location
0    False  False    False     False    False              False
1    False  False    False     False    False              False
2    False  False    False     False    False              False
3    False  False    False     False    False              False
4    False  False    False     False    False              False

In [68]:
df[['OrderID','Category','Revenue']].agg(['min','max','mean'])

     OrderID Category Revenue
min    False    False   False
max    False    False   False
mean     0.0      0.0     0.0